---
name: Terraform

# Triggers the workflow on push or pull request events
on: [push, pull_request]  # yamllint disable-line rule:truthy

jobs:
  job1:
    runs-on: ubuntu-latest
    name: terraform validate
    steps:
      - name: Github checkout repository
        id: git-checkout
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform fmt
        id: terraform-fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: terraform-init
        run: terraform init

      - name: Terraform validate
        id: terraform-validate
        run: terraform validate -no-color
