name: Validate

defaults:
  run:
    working-directory: ${{ env.tf_actions_working_dir }}

on:
  - push
  - pull_request

- name: HashiCorp - Setup Terraform
  uses: hashicorp/setup-terraform@v1.2.1

- name: Terraform fmt
  id: fmt
  run: terraform fmt -check
  continue-on-error: true

- name: Terraform Init
  id: init
  run: terraform init

- name: Terraform Validate
  id: validate
  run: terraform validate -no-color

